name: Run Tests

on:
  push:
    branches: [ master ]
    paths:  # Run tests when there are changes to src or tests
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches: [ master ]
    paths:  # Run tests when there are changes to src or tests
      - 'src/**'
      - 'tests/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create and activate virtual environment
      run: |
        uv venv -p 3.12 --seed
        echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv pip install --no-cache-dir -e ".[test,lint]"

    - name: Check formatting with black
      run: |
        black --check .

    - name: Lint with ruff
      run: |
        ruff check .
        ruff format --check .

    - name: Run unit tests
      run: |
        pytest -v -m unit

    - name: Run integration tests
      run: |
        pytest -v -m integration
